[package]
name = "chitin-wgpu"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { version = "30", default-features = false, features = ["vulkan", "wgsl"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "30", default-features = false, features = ["webgpu", "wgsl"] }

[lints]
workspace = true
