//! Typed, schema-like views over generic CIF loop categories.
//!
//! The generic CIF parser owns syntax and source values. This layer compiles a
//! category's column names once, then exposes typed row accessors generated by
//! `chitin-bio-macros`. Biological projection remains in category modules.

use std::collections::HashMap;
use std::marker::PhantomData;

use super::cif::{CifCategory, CifDocument, CifValue};
use crate::structure::MmcifParseError;

/// A borrowed loop with column names indexed once for repeated row access.
#[derive(Debug)]
pub(crate) struct CategoryView<'a> {
  columns: HashMap<&'a str, usize>,
  rows: CategoryRows<'a>,
}

/// Stores either loop rows or the single logical row formed by scalar items.
#[derive(Debug)]
enum CategoryRows<'a> {
  Loop(&'a [Vec<CifValue>]),
  Scalars(Vec<(&'a str, &'a CifValue)>),
}

impl<'a> CategoryView<'a> {
  /// Finds the first loop or scalar category belonging to `category` in source order.
  pub(crate) fn from_document(document: &'a CifDocument, category: &str) -> Option<Self> {
    let prefix = format!("_{category}.");
    for block in &document.blocks {
      if let Some((tags, rows)) = block.categories.iter().find_map(|value| {
        let CifCategory::Loop { tags, rows } = value else {
          return None;
        };
        tags.iter().any(|tag| tag.starts_with(&prefix)).then_some((tags, rows))
      }) {
        return Some(Self {
          columns: tags
            .iter()
            .enumerate()
            .map(|(index, tag)| (tag.as_str(), index))
            .collect(),
          rows: CategoryRows::Loop(rows),
        });
      }

      let scalar_items = block
        .categories
        .iter()
        .filter_map(|value| match value {
          CifCategory::Item { tag, value } if tag.starts_with(&prefix) => Some((tag.as_str(), value)),
          _ => None,
        })
        .collect::<Vec<_>>();
      if !scalar_items.is_empty() {
        return Some(Self {
          columns: HashMap::new(),
          rows: CategoryRows::Scalars(scalar_items),
        });
      }
    }
    None
  }

  /// Returns rows with stable one-based category row numbers.
  pub(crate) fn rows(&self) -> impl Iterator<Item = CategoryRow<'_>> {
    let columns = &self.columns;
    let mut index = 0;
    std::iter::from_fn(move || {
      index += 1;
      let values = match &self.rows {
        CategoryRows::Loop(rows) => rows.get(index - 1).map(|row| RowValues::Loop(row.as_slice())),
        CategoryRows::Scalars(values) if index == 1 => Some(RowValues::Scalars(values)),
        CategoryRows::Scalars(_) => None,
      }?;
      Some(CategoryRow {
        columns,
        values,
        row_number: index,
      })
    })
  }
}

/// The value storage behind one generic category row.
#[derive(Debug, Clone, Copy)]
enum RowValues<'a> {
  Loop(&'a [CifValue]),
  Scalars(&'a [(&'a str, &'a CifValue)]),
}

/// A typed borrowed category generated from the local mmCIF schema.
#[derive(Debug)]
pub(crate) struct TypedCategory<'a, Schema> {
  view: CategoryView<'a>,
  schema: PhantomData<fn() -> Schema>,
}

impl<'a, Schema> TypedCategory<'a, Schema> {
  /// Finds a category and attaches its generated schema marker.
  pub(crate) fn from_document(document: &'a CifDocument, category: &str) -> Option<Self> {
    CategoryView::from_document(document, category).map(|view| Self {
      view,
      schema: PhantomData,
    })
  }

  /// Returns typed rows in source order.
  pub(crate) fn rows(&self) -> impl Iterator<Item = TypedRow<'_, Schema>> {
    self.view.rows().map(|raw| TypedRow {
      raw,
      schema: PhantomData,
    })
  }
}

/// One category row carrying a generated schema marker.
#[derive(Debug, Clone, Copy)]
pub(crate) struct TypedRow<'a, Schema> {
  pub(crate) raw: CategoryRow<'a>,
  schema: PhantomData<fn() -> Schema>,
}

impl<Schema> TypedRow<'_, Schema> {
  /// Returns the one-based row number within the category.
  pub(crate) const fn row_number(self) -> usize {
    self.raw.row_number()
  }
}

/// One borrowed category row with typed conversion helpers.
#[derive(Debug, Clone, Copy)]
pub(crate) struct CategoryRow<'a> {
  columns: &'a HashMap<&'a str, usize>,
  values: RowValues<'a>,
  row_number: usize,
}

impl<'a> CategoryRow<'a> {
  /// Returns the one-based row number within the category loop.
  pub(crate) const fn row_number(self) -> usize {
    self.row_number
  }

  /// Returns the first present text value among equivalent item names.
  pub(crate) fn optional_text(self, tags: &[&str]) -> Option<&'a str> {
    tags.iter().find_map(|tag| {
      self
        .value(tag)
        .and_then(CifValue::as_text)
        .filter(|value| !value.trim().is_empty())
    })
  }

  /// Returns a raw value by tag from either a loop or scalar category row.
  fn value(self, tag: &str) -> Option<&'a CifValue> {
    match self.values {
      RowValues::Loop(values) => self.columns.get(tag).and_then(|index| values.get(*index)),
      RowValues::Scalars(values) => values.iter().find_map(|(name, value)| (*name == tag).then_some(*value)),
    }
  }

  /// Reads an optional signed integer from equivalent item names.
  pub(crate) fn optional_i32(self, tags: &[&str], field: &'static str) -> Result<Option<i32>, MmcifParseError> {
    let Some(value) = self.optional_text(tags) else {
      return Ok(None);
    };
    value.parse().map(Some).map_err(|_| MmcifParseError::InvalidField {
      row: self.row_number,
      field,
      value: value.to_owned(),
    })
  }

  /// Reads an optional floating-point value.
  pub(crate) fn optional_f32(self, tags: &[&str], field: &'static str) -> Result<Option<f32>, MmcifParseError> {
    let Some(value) = self.optional_text(tags) else {
      return Ok(None);
    };
    let parsed = value.parse::<f32>().map_err(|_| MmcifParseError::InvalidField {
      row: self.row_number,
      field,
      value: value.to_owned(),
    })?;
    if parsed.is_finite() {
      Ok(Some(parsed))
    } else {
      Err(MmcifParseError::InvalidField {
        row: self.row_number,
        field,
        value: value.to_owned(),
      })
    }
  }
}
