//! Typed, schema-like views over generic CIF loop categories.
//!
//! The generic CIF parser owns syntax and source values. This layer compiles a
//! category's column names once, then exposes typed row accessors generated by
//! `chitin-bio-macros`. Biological projection remains in category modules.

use std::collections::HashMap;
use std::marker::PhantomData;

use super::cif::{CifCategory, CifDocument, CifValue};
use crate::structure::MmcifParseError;

/// A borrowed loop with column names indexed once for repeated row access.
#[derive(Debug)]
pub(crate) struct CategoryView<'a> {
  columns: HashMap<&'a str, usize>,
  rows: &'a [Vec<CifValue>],
}

impl<'a> CategoryView<'a> {
  /// Finds the first loop belonging to `category` in source order.
  pub(crate) fn from_document(document: &'a CifDocument, category: &str) -> Option<Self> {
    let prefix = format!("_{category}.");
    document
      .blocks
      .iter()
      .flat_map(|block| &block.categories)
      .find_map(|value| {
        let CifCategory::Loop { tags, rows } = value else {
          return None;
        };
        tags.iter().any(|tag| tag.starts_with(&prefix)).then(|| Self {
          columns: tags
            .iter()
            .enumerate()
            .map(|(index, tag)| (tag.as_str(), index))
            .collect(),
          rows,
        })
      })
  }

  /// Returns rows with stable one-based category row numbers.
  pub(crate) fn rows(&self) -> impl Iterator<Item = CategoryRow<'_>> {
    self.rows.iter().enumerate().map(|(index, values)| CategoryRow {
      columns: &self.columns,
      values,
      row_number: index + 1,
    })
  }
}

/// A typed borrowed category generated from the local mmCIF schema.
#[derive(Debug)]
pub(crate) struct TypedCategory<'a, Schema> {
  view: CategoryView<'a>,
  schema: PhantomData<fn() -> Schema>,
}

impl<'a, Schema> TypedCategory<'a, Schema> {
  /// Finds a category and attaches its generated schema marker.
  pub(crate) fn from_document(document: &'a CifDocument, category: &str) -> Option<Self> {
    CategoryView::from_document(document, category).map(|view| Self {
      view,
      schema: PhantomData,
    })
  }

  /// Returns typed rows in source order.
  pub(crate) fn rows(&self) -> impl Iterator<Item = TypedRow<'_, Schema>> {
    self.view.rows().map(|raw| TypedRow {
      raw,
      schema: PhantomData,
    })
  }
}

/// One category row carrying a generated schema marker.
#[derive(Debug, Clone, Copy)]
pub(crate) struct TypedRow<'a, Schema> {
  pub(crate) raw: CategoryRow<'a>,
  schema: PhantomData<fn() -> Schema>,
}

impl<Schema> TypedRow<'_, Schema> {
  /// Returns the one-based row number within the category.
  pub(crate) const fn row_number(self) -> usize {
    self.raw.row_number()
  }
}

/// One borrowed category row with typed conversion helpers.
#[derive(Debug, Clone, Copy)]
pub(crate) struct CategoryRow<'a> {
  columns: &'a HashMap<&'a str, usize>,
  values: &'a [CifValue],
  row_number: usize,
}

impl<'a> CategoryRow<'a> {
  /// Returns the one-based row number within the category loop.
  pub(crate) const fn row_number(self) -> usize {
    self.row_number
  }

  /// Returns the first present text value among equivalent item names.
  pub(crate) fn optional_text(self, tags: &[&str]) -> Option<&'a str> {
    tags.iter().find_map(|tag| {
      self
        .columns
        .get(tag)
        .and_then(|index| self.values.get(*index))
        .and_then(CifValue::as_text)
        .filter(|value| !value.trim().is_empty())
    })
  }

  /// Reads an optional signed integer from equivalent item names.
  pub(crate) fn optional_i32(self, tags: &[&str], field: &'static str) -> Result<Option<i32>, MmcifParseError> {
    let Some(value) = self.optional_text(tags) else {
      return Ok(None);
    };
    value.parse().map(Some).map_err(|_| MmcifParseError::InvalidField {
      row: self.row_number,
      field,
      value: value.to_owned(),
    })
  }

  /// Reads an optional floating-point value.
  pub(crate) fn optional_f32(self, tags: &[&str], field: &'static str) -> Result<Option<f32>, MmcifParseError> {
    let Some(value) = self.optional_text(tags) else {
      return Ok(None);
    };
    let parsed = value.parse::<f32>().map_err(|_| MmcifParseError::InvalidField {
      row: self.row_number,
      field,
      value: value.to_owned(),
    })?;
    if parsed.is_finite() {
      Ok(Some(parsed))
    } else {
      Err(MmcifParseError::InvalidField {
        row: self.row_number,
        field,
        value: value.to_owned(),
      })
    }
  }
}
