//! Optional timing and workload diagnostics for SES generation.

use std::time::{Duration, Instant};

use super::{
  DISTANCE_FIELD_RANGE, ImplicitAtom, SMOOTHING_ITERATIONS, atom_bounds, budgeted_grid_layout,
  contour::contour_field,
  field::{atom_surface_distance, compose_inner_surface_field_in_place, probe_surface_distance, sample_field},
  implicit_atom_groups, merge_close_probe_centers,
  postprocess::{orient_inner_surface, recompute_inner_surface_normals, smooth_mesh},
  spatial::{AtomGrid, PointGrid},
  types::{
    MolecularSurfaceArtifact, MolecularSurfaceRequest, SesParameters, SurfaceDomainArtifact, SurfaceGeometrySource,
    SurfaceMesh,
  },
};
use crate::structure::StructureScene;

/// Stage timings and intermediate sizes collected by an explicit profiling run.
#[cfg(feature = "surface-profiling")]
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct MolecularSurfaceTimings {
  /// Time spent selecting atoms and resolving calculation domains.
  pub atom_grouping: Duration,
  /// Time spent building atom and probe-center spatial indices.
  pub spatial_indexing: Duration,
  /// Time spent sampling the expanded-atom distance fields.
  pub sas_field_sampling: Duration,
  /// Time spent extracting first-pass solvent-accessible contours.
  pub sas_contouring: Duration,
  /// Time spent merging first-pass contour vertices into probe centers.
  pub probe_center_merging: Duration,
  /// Time spent sampling probe-center distance fields.
  pub ses_field_sampling: Duration,
  /// Time spent extracting second-pass solvent-excluded contours.
  pub ses_contouring: Duration,
  /// Time spent filling the SAS exterior into the probe distance field.
  pub inner_field_composition: Duration,
  /// Time spent making retained triangle winding consistent.
  pub orientation: Duration,
  /// Time spent smoothing retained meshes.
  pub smoothing: Duration,
  /// Time spent rebuilding final vertex normals.
  pub normal_recomputation: Duration,
  /// Sum of scalar-grid points processed across all domains.
  pub grid_points: usize,
  /// Number of merged probe centers across all domains.
  pub probe_centers: usize,
  /// Number of triangles produced by first-pass contours.
  pub sas_triangles: usize,
  /// Number of triangles retained in final SES meshes.
  pub ses_triangles: usize,
}

/// Complete surface artifact paired with opt-in generation diagnostics.
#[cfg(feature = "surface-profiling")]
#[derive(Debug, PartialEq)]
pub struct MolecularSurfaceProfile {
  /// Implicit rendering surface generated by the profiled run.
  pub artifact: MolecularSurfaceArtifact,
  /// Aggregated timings and intermediate sizes for every calculation domain.
  pub timings: MolecularSurfaceTimings,
}

/// Generates a surface while collecting stage-level CPU diagnostics.
#[cfg(feature = "surface-profiling")]
pub fn profile_molecular_surface(scene: &StructureScene, request: MolecularSurfaceRequest) -> MolecularSurfaceProfile {
  let mut metrics = SurfaceGenerationMetrics::new();
  let atom_groups = metrics.measure(SurfaceStage::AtomGrouping, || implicit_atom_groups(scene, request));
  let domains = atom_groups
    .into_iter()
    .map(|(chain_id, atoms)| SurfaceDomainArtifact {
      chain_id,
      mesh: ses_mesh_for_atoms_profiled(atoms, request.ses, &mut metrics),
    })
    .collect();
  MolecularSurfaceProfile {
    artifact: MolecularSurfaceArtifact {
      source: SurfaceGeometrySource::ImplicitGrid(request),
      domains,
    },
    timings: metrics.timings,
  }
}

/// Timed stages in the sampled-grid SES pipeline.
#[cfg(feature = "surface-profiling")]
#[derive(Clone, Copy)]
enum SurfaceStage {
  AtomGrouping,
  SpatialIndexing,
  SasFieldSampling,
  SasContouring,
  ProbeCenterMerging,
  SesFieldSampling,
  SesContouring,
  InnerFieldComposition,
  Orientation,
  Smoothing,
  NormalRecomputation,
}

/// Internal accumulator compiled into both paths but activated only on request.
#[cfg(feature = "surface-profiling")]
struct SurfaceGenerationMetrics {
  timings: MolecularSurfaceTimings,
}

#[cfg(feature = "surface-profiling")]
impl SurfaceGenerationMetrics {
  /// Creates an enabled profiler or a zero-overhead diagnostic sink.
  fn new() -> Self {
    Self {
      timings: MolecularSurfaceTimings::default(),
    }
  }

  /// Measures one coarse pipeline stage when profiling is enabled.
  fn measure<T>(&mut self, stage: SurfaceStage, operation: impl FnOnce() -> T) -> T {
    let started_at = Instant::now();
    let result = operation();
    self.record_duration(stage, started_at.elapsed());
    result
  }

  /// Adds a completed stage duration to the aggregate report.
  fn record_duration(&mut self, stage: SurfaceStage, duration: Duration) {
    let target = match stage {
      SurfaceStage::AtomGrouping => &mut self.timings.atom_grouping,
      SurfaceStage::SpatialIndexing => &mut self.timings.spatial_indexing,
      SurfaceStage::SasFieldSampling => &mut self.timings.sas_field_sampling,
      SurfaceStage::SasContouring => &mut self.timings.sas_contouring,
      SurfaceStage::ProbeCenterMerging => &mut self.timings.probe_center_merging,
      SurfaceStage::SesFieldSampling => &mut self.timings.ses_field_sampling,
      SurfaceStage::SesContouring => &mut self.timings.ses_contouring,
      SurfaceStage::InnerFieldComposition => &mut self.timings.inner_field_composition,
      SurfaceStage::Orientation => &mut self.timings.orientation,
      SurfaceStage::Smoothing => &mut self.timings.smoothing,
      SurfaceStage::NormalRecomputation => &mut self.timings.normal_recomputation,
    };
    *target += duration;
  }

  /// Records intermediate workload sizes for an enabled profiling run.
  fn record_sizes(&mut self, grid_points: usize, probe_centers: usize, sas_triangles: usize, ses_triangles: usize) {
    self.timings.grid_points += grid_points;
    self.timings.probe_centers += probe_centers;
    self.timings.sas_triangles += sas_triangles;
    self.timings.ses_triangles += ses_triangles;
  }
}

/// Runs the CPU SES kernel while recording coarse stage diagnostics.
#[cfg(feature = "surface-profiling")]
fn ses_mesh_for_atoms_profiled(
  atoms: Vec<ImplicitAtom>,
  parameters: SesParameters,
  metrics: &mut SurfaceGenerationMetrics,
) -> SurfaceMesh {
  if atoms.is_empty() {
    return SurfaceMesh::default();
  }
  let atom_grid = metrics.measure(SurfaceStage::SpatialIndexing, || AtomGrid::new(atoms));

  let (atom_bounds_min, atom_bounds_max) = atom_bounds(&atom_grid.atoms);
  let probe_radius = parameters.probe_radius();
  let preferred_spacing = parameters.grid_spacing();
  let margin = atom_grid.max_radius + 2.0 * probe_radius + preferred_spacing;
  let bounds_min = atom_bounds_min - glam::Vec3::splat(margin);
  let bounds_max = atom_bounds_max + glam::Vec3::splat(margin);
  let extent = bounds_max - bounds_min;
  let (spacing, dimensions) = budgeted_grid_layout(extent, preferred_spacing, parameters.max_grid_points());

  let grid_points = dimensions.into_iter().product();
  let sas_field = metrics.measure(SurfaceStage::SasFieldSampling, || {
    sample_field(bounds_min, spacing, dimensions, |position| {
      atom_surface_distance(position, &atom_grid, probe_radius, spacing)
    })
  });
  drop(atom_grid);
  let sas_mesh = metrics.measure(SurfaceStage::SasContouring, || {
    contour_field(bounds_min, spacing, dimensions, &sas_field)
  });
  if sas_mesh.vertices.is_empty() {
    return SurfaceMesh::default();
  }

  let sas_triangles = sas_mesh.indices.len() / 3;
  let probe_centers = metrics.measure(SurfaceStage::ProbeCenterMerging, || {
    merge_close_probe_centers(&sas_mesh, 0.35 * spacing)
  });
  let probe_center_count = probe_centers.len();
  drop(sas_mesh);
  let probe_grid = metrics.measure(SurfaceStage::SpatialIndexing, || {
    PointGrid::new(probe_centers, probe_radius + DISTANCE_FIELD_RANGE * spacing)
  });
  let mut inner_surface_field = metrics.measure(SurfaceStage::SesFieldSampling, || {
    sample_field(bounds_min, spacing, dimensions, |position| {
      probe_surface_distance(position, &probe_grid, probe_radius, spacing)
    })
  });
  drop(probe_grid);
  metrics.measure(SurfaceStage::InnerFieldComposition, || {
    compose_inner_surface_field_in_place(&mut inner_surface_field, &sas_field);
  });
  drop(sas_field);
  let mut mesh = metrics.measure(SurfaceStage::SesContouring, || {
    contour_field(bounds_min, spacing, dimensions, &inner_surface_field)
  });
  metrics.measure(SurfaceStage::Orientation, || {
    orient_inner_surface(&mut mesh, bounds_min, spacing, dimensions, &inner_surface_field);
  });
  metrics.measure(SurfaceStage::Smoothing, || {
    smooth_mesh(&mut mesh, SMOOTHING_ITERATIONS);
  });
  metrics.measure(SurfaceStage::NormalRecomputation, || {
    recompute_inner_surface_normals(&mut mesh, bounds_min, spacing, dimensions, &inner_surface_field);
  });
  metrics.record_sizes(grid_points, probe_center_count, sas_triangles, mesh.indices.len() / 3);
  mesh
}
