[package]
name = "chitin-desktop"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log = "0.4.33"
env_logger = "0.10"
chitin-utils = { path = "../chitin-utils" }
chitin-ui = { path = "../chitin-ui" }
chitin-wgpu = { path = "../chitin-wgpu" }
gpui = { package = "gpui-ce", git = "https://github.com/chitin-dev/gpui-wgpu", rev = "32197ffc3febdb2921d178c7f4802d73702f9b62" }
wgpu = { version = "30", default-features = false, features = ["vulkan", "wgsl"] }

[dev-dependencies]
bytemuck = "1.24"
glam = "0.33"

[lints]
workspace = true
